# Generated by Django 5.1.3 on 2024-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_cours_etudiant_professeur_questionanswers_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswers',
            name='numero',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
