# Generated by Django 5.1.3 on 2024-12-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_questionanswers_numero_questionanswers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
